<template>
    <div class="terms-container">
        <h1>Terms & Conditions</h1>
        <div class="terms-content">
            <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under
                as applicable and the amended provisions pertaining to electronic records in various statutes as amended
                by the Information Technology Act, 2000. This electronic record is generated by a computer system and
                does not require any physical or digital signatures.</p>

            <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy
                policy and Terms of Use for access or usage of domain name nimitsavant.me ("Website"), including the
                related mobile site and mobile application (hereinafter referred to as "Platform").</p>

            <p>The Platform is owned by NitMit Solutions, a company incorporated under the Companies Act, 1956 with its
                registered office at 2nd Floor, Savant House, Opp: Maharashtra Lodge, Dandia Bazar, Gujarat, 390001
                (hereinafter referred to as "Platform Owner", "we", "us", "our").</p>

            <h2>1. Acceptance of Terms</h2>
            <p>Your use of the Platform and services and tools are governed by the following terms and conditions
                ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated
                herein by way of reference. By mere use of the Platform, You shall be contracting with the Platform
                Owner and these terms and conditions including the policies constitute Your binding obligations, with
                Platform Owner.</p>

            <h2>2. Modifications to Terms</h2>
            <p>These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to
                periodically review these Terms of Use to stay informed of updates.</p>

            <h2>3. User Agreement</h2>
            <p>For the purpose of these Terms of Use, wherever the context so requires "you", "your" or "user" shall
                mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>

            <h2>4. Access and Use</h2>
            <p>To access and use the Services, you agree to provide true, accurate and complete information to us during
                and after registration, and you shall be responsible for all acts done through the use of your
                registered account on the Platform.</p>

            <h2>5. Disclaimer</h2>
            <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
                performance, completeness or suitability of the information and materials offered on this website or
                through the Services, for any specific purpose.</p>

            <h2>6. Intellectual Property</h2>
            <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not
                have any authority to claim any intellectual property rights, title, or interest in its contents.</p>

            <h2>7. Liability</h2>
            <p>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or
                punitive damages, including without limitation damages for loss of profits or revenues, business
                interruption, loss of business opportunities, loss of data or loss of other economic interests.</p>

            <h2>8. Governing Law</h2>
            <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and
                construed in accordance with the laws of India. All disputes arising out of or in connection with these
                Terms shall be subject to the exclusive jurisdiction of the courts in Vadodara, Gujarat.</p>
        </div>
    </div>
</template>

<script lang="ts">
export default {
    name: 'TermsAndConditions'
}
</script>

<style scoped>
.terms-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.terms-content {
    line-height: 1.6;
}

h1 {
    font-size: 2.5rem;
    margin-bottom: 2rem;
    color: #333;
}

h2 {
    font-size: 1.5rem;
    margin-top: 2rem;
    margin-bottom: 1rem;
    color: #444;
}

p {
    margin-bottom: 1rem;
    color: #666;
}
</style>