#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking build..."
yarn build

if [ $? -ne 0 ]; then
  echo "Build failed, aborting push"
  exit 1
fi

echo "Running dev server..."
yarn dev

if [ $? -ne 0 ]; then
  echo "Dev server failed, aborting push"
  exit 1
fi